Unstructured-IO/unstructured-python-client

README.md
It looks like we no longer support passing in a Security object and instead have the users directly assign `api_key_auth`, looks like this part of the README just needed the respective bump.
=> docs: bump the change the base url example code per recent release changes

README.md
Closes #11 
The autogenerated code has made this object less verbose. We need to update this in the example.
=> chore: fix example in readme for updated Files object

.genignore, Makefile, tests/test_utils_retries.py
This PR adds a test that checks if the retry logic is operating using custom retry configurations (for the sake of time when running the test). This test also requires that an `UNS_API_KEY` be set in your local environment. This can be done by exporting it in your bash session (`export UNS_API_KEY=<api_key>`).
Additionally, it adds a `.genignore` file, which is used to tell Speakeasy to _ignore_ this test file so it is not overwritten.
=> chore: create test

_test_unstructured_client/test__decorators.py, src/unstructured_client/general.py, src/unstructured_client/sdk.py, src/unstructured_client/utils/_decorators.py
Final PR for closing #30 
This PR adds a decorator to the `partition` method of the `General` class to catch if a 401 error is being raised while `server_url` is `None` and add a warning message.
Testing
```
from unstructured_client.models import shared
from unstructured_client import UnstructuredClient
FAKE_KEY = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
client = UnstructuredClient(
api_key_auth=FAKE_KEY,
)
filename = "_sample_docs/layout-parser-paper-fast.pdf"
with open(filename, "rb") as f:
files=shared.Files(
content=f.read(),
file_name=filename,
)
req = shared.PartitionParameters(
files=files,
)
client.general.partition(req)
```
=> chore: suggest url if 401

Makefile, src/unstructured_client/utils/_decorators.py
follow-up from #30 and #32
This adds a `make lint` command that uses the `pylintrc` file Speakeasy creates so that we can check if our changes will pass.
This also moves a global variable to the appropriate scope so the linting passes.
=> chore: add 'make lint' command and address linting error

.github/workflows/speakeasy_sdk_generation.yml
We're now generating our openapi spec out of FastAPI. This means we can go straight to the hosted spec instead of duplicating the file in github.
=> Move the openapi source of truth

_test_unstructured_client/test_utils_retries.py, src/unstructured_client/general.py, src/unstructured_client/sdk.py, src/unstructured_client/utils/_human_utils.py, src/unstructured_client/utils/retries.py
Closes #31 
Adds function to log retries. A function is used instead of a decorator because it is not possible to use a decorator to access the `while` loop in `retry_with_backoff` where retries are made.
Also renames `_decorators.py` to `_human_utils.py`
In `_human_utils.py`, `from unstructured_client.models import errors` is moved to prevent a circular import error between the `models` and `utils` modules.
- from your unstructured venv, `pip uninstall unstructured-client`
- navigate to unstructured-python-client, check out to this branch, and `pip install -e .`
- `pip install requests_mock`
- open a python shell and run the following:
```
from unstructured.partition.api import partition_via_api
import requests_mock
with requests_mock.Mocker() as mock: …
```
=> chore: log retry

.github/workflows/speakeasy_sdk_generation.yml
This reverts commit ba95fb0f0adfbc374d320b31e18a672190b90a18. See https://github.com/Unstructured-IO/unstructured-api/pull/369
=> Revert "Move the openapi source of truth"

.github/workflows/speakeasy_sdk_publish.yaml
Mirror of the js change here: https://github.com/Unstructured-IO/unstructured-js-client/pull/38/files
We'd like to coordinate some breaking changes in the clients before starting to publish again.
=> Disable the publish job

.speakeasy/workflow.yaml
The interface will change slightly, and we'll provide a migration guide before enabling publishing again.
=> chore: Use the hosted api spec for generation

.speakeasy/workflow.yaml
Setup for integrating Speakeasy generated code snippets directly into our Mintlify docs repo
https://www.speakeasyapi.dev/docs/mintlify#manual-setup
Also see https://github.com/Unstructured-IO/docs/pull/36
=> chore/docs: code samples for docs repo

_test_unstructured_client/integration/test_integration_freemium.py, src/unstructured_client/_hooks/custom/split_pdf_hook.py
- to allow Windows to run pdf splitting with the sdk we switch from Process based to Thread based multiprocessing
- add integration test to verify the client can handle pdf splitting with successful server response and unsuccessful responses
- macOS
- Linux (ci)
- Windows 11 (with powershell)
- WSL (ubuntu)
=> feat: use ThreadPoolExecutor

_test_unstructured_client/integration/test_decorators.py
Previously it would just print `unexpected error` and exit all of the tests, giving no reason or error message why and what tests failed.
=> Fix error messages for failed integration tests

overlay_client.yaml
See #94 for example. Our api uses `anyOf` for optional params, and if there's no default value, the client sets the default __SPEAKEASY_UNSET__. This string gets sent for all optional params and causes the server to basically always return a validation error.
We need to add a null default like so:
```
"combine_under_n_chars": {
"anyOf": [
{
"type": "integer",
"default": null
},
{
"type": "null"
}
],
},
```
However, doing this on the server breaks the js-client. Over there, optional params are undefined by default, and adding a null default causes us to send a literal `null`, causing the same validation issues.
Thus the fix is to set the defaults only on the python side and remove the workaround on the server.
To test, run `make client-generate && make test`.
=> fix: Fix optional params defaulting to __SPEAKEASY_UNSET__

src/unstructured_client/_hooks/custom/split_pdf_hook.py
We're seeing an issue where the nest_asyncio.apply() workaround for nested loops is breaking when we're dealing with a `uvloop`. We need to investigate further, or remove the bandaid solution. In the meantime, we can unblock a simple import of the client in these environments by doing the apply only when the hook is run.
=> fix/Move the nest-asyncio apply into an init hook

README.md
Our docs page will be the source of truth, and the readme can have some general information from the autogenerated sections.
Changes:
* Link to our docs at the top
* Remove the manually created usage snippet and swap out for the autogenerated one. This way, the readme stays up to date while we focus on the docs page.
* Bring back autogenerated error handling - this will populate the next time the client regens
=> Refer to Unstructured docs in readme

README.md
The autogenerated example is inconsistent with our hosted docs. Remove this section and copy the usage snippet from the docs. Also, add a note for the new page range feature.
=> chore: Update usage example to be consistent with docs

_test_unstructured_client/integration/test_integration_freemium.py, _test_unstructured_client/unit/test_custom_hooks.py, gen.yaml, src/unstructured_client/_hooks/custom/suggest_defining_url.py
The default server url is changing to serverless. Therefore, if you get a 401, we should suggest that you meant to use the free api. Also, bump the minor version in anticipation of the url change.
=> chore: update 401 warning hook for new default url

Makefile, _test_unstructured_client/integration/test_integration_freemium.py, src/unstructured_client/_hooks/custom/split_pdf_hook.py
PDF page splitting uses asyncio but the SDK is not async. Therefore, we had to manage our own event loop, which can lead to issues in other event loop contexts. Uvloop is one context that does not allow us to use nested event loops. When we find ourselves in a uvloop.Loop, we have to fallback to non splitting mode. #135 will make the whole SDK async so we don't have to hack this.
Closes #133
=> fix: Do not throw error when in a uvloop context

src/unstructured_client/_hooks/custom/split_pdf_hook.py
Certain environments throw a `RuntimeError: There is no current event loop in thread 'asyncio_0'` when we try to check if we're able to use the splitting code. In this case, return False so we can fallback to non split mode.
Once this is merged, I can regenerate the client to publish 0.25.4.
=> fix: handle RuntimeError when checking if we can use pdf split mode

src/unstructured_client/_hooks/custom/pdf_utils.py
When we load a PdfReader with `strict=False`, we can get warnings from pypdf. Unless an error is thrown, these do not affect processing, so let's just suppress the pypdf log level.
=> chore: Remove warning logs from pypdf

_test_unstructured_client/unit/test_custom_hooks.py
Status code 500 doesn't retry now, so changed status code from `500` to `502` in `test_unit_retry_with_backoff_does_retry`
=> fix: test retry with 502 status code instead of 500

.github/workflows/ci.yaml, .github/workflows/speakeasy_sdk_generation.yml, README.md
* Run the right install command before running `make lint`
* Fix indentation error with the new `patch-custom-code` step
=> fix: Fix CI failures after new 0.26.0 (beta) merge

.github/workflows/speakeasy_sdk_generation.yml, Makefile, _test_unstructured_client/unit/test_split_pdf_hook.py, src/unstructured_client/_hooks/custom/form_utils.py, src/unstructured_client/_hooks/custom/pdf_utils.py, src/unstructured_client/_hooks/custom/request_utils.py, src/unstructured_client/_hooks/custom/split_pdf_hook.py
Fix all mypy errors due to incorrect typing after the SDK v2 merge (https://github.com/Unstructured-IO/unstructured-python-client/pull/135). Logic changes should be minimal, this is mostly to change type hints where a `httpx.Response` is used instead of a `requests.Response`, etc. I removed some `form_utils.py` functions where we no longer need to convert a httpx request back to Requests. There's more we can cleanup in here, but let's get the V2 migration settled first.
Add mypy to `make lint` so that we can cath these errors before merging. The publish job runs a full linter suite, and these changes made it to main but broke the publish job.
Also, remove the Patch Custom Code step that I added to the generate. This broke the job. There are some minor changes to the Speakeasy code on the …
=> fix: Address mypy typing errors in v2 SDK

src/unstructured_client/_hooks/custom/split_pdf_hook.py
The `import uvloop` line here needs to:
* Ignore a pylint `import-outside-toplevel` warning
* Ignore a mypy error if stubs are not present (uvloop is not a dependency, so it's not actually installed in CI)
These comments were not ignoring both errors, turns out we need to flip the order.
=> fix: Fix a mypy failure in the generate action

.github/workflows/ci.yaml, gen.yaml, src/unstructured_client/_hooks/custom/split_pdf_hook.py
We're still seeing some ReadTimeout errors when a pdf is split and sent for `hi_res` processing. For now, let's raise the default timeout to 30 minutes, and allow for tweaking via the UNSTRUCTURED_CLIENT_TIMEOUT_MINUTES. Users should not generally need to adjust this, but it may help us debug their environment. When our split pdf hook is able to reuse the SDK logic, the client timeout will be exposed as a parameter, and we can remove this variable.
Other changes:
* Update CI workflow to run against release branches. This 0.25.x branch should be running tests as long as it sticks around.
* Bump the gen.yaml version to 0.25.7. The next generate/publish job on this branch will use this.
=> fix: raise httpx timeout value for split pdf requests

CHANGELOG.md, _test_unstructured_client/integration/test_integration_freemium.py, src/unstructured_client/_hooks/custom/split_pdf_hook.py
`split_pdf_hook.py` does not support multiple concurrent files. This is because we store the split request tasks in `self.coroutines_to_execute[operation_id]`, where `operation_id` is just the string "partition". Therefore, if we send two concurrent docs using the same SDK, they'll both try to await the same list of coroutines. This could result in interleaved results, but mostly it breaks with `RuntimeError: coroutine is being awaited already`, as the second request gets ready to await its requests. This will block anyone trying to use the new `partition_async` to fan out their pdfs.
Note that the js/ts client also has this issue.
We need to use an actual id to index into `coroutines_to_execute`. In `before_request`, let's make a uuid and build up the list of coroutines for this doc. We …
=> fix: Allow split page logic to process files concurrently

gen.yaml
Bring the min version to the main branch - this is done for the 0.25.x release [here](https://github.com/Unstructured-IO/unstructured-python-client/pull/176).
Also, remove jupyter as a dev dependency. You're free to install it for local work, but we don't need to pull it on every `poetry install`. Case in point, it was causing an issue in the [generate action](https://github.com/Unstructured-IO/unstructured-python-client/actions/runs/10947329413/job/30395826215). The jupyter install was trying to pull in `psutil`, which needed to be built from source. However, our generate environment doesn't have all the build tools set up, so let's remove the need for `psutil` entirely.
=> chore: Add min version requirement for `cryptography`

_test_unstructured_client/integration/test_decorators.py, _test_unstructured_client/unit/test_split_pdf_hook.py, src/unstructured_client/_hooks/custom/pdf_utils.py
Instead of manually checking filename with `.pdf` extension and return is_pdf = false -> use currently pdf library to read file content to decide if the file content is valid pdf
=> chore Use pdf library to check file without extension

.github/workflows/ci.yaml, _test_unstructured_client/integration/test_decorators.py, _test_unstructured_client/integration/test_integration_freemium.py, _test_unstructured_client/unit/test_custom_hooks.py, _test_unstructured_client/unit/test_split_pdf_hook.py, src/unstructured_client/_hooks/custom/clean_server_url_hook.py, src/unstructured_client/_hooks/custom/form_utils.py, src/unstructured_client/_hooks/custom/logger_hook.py, src/unstructured_client/_hooks/custom/pdf_utils.py, src/unstructured_client/_hooks/custom/suggest_defining_url.py
Adds `from __future__ import annotations` to all custom code files to enable forward references to contemporary type hints such as `dict` and ` list`. Also fixes a `TypeAlias` and enables python `3.8` checks (resolves https://github.com/Unstructured-IO/unstructured-python-client/issues/138)
=> feat: py 3.8 support

README.md, gen.yaml
Bring back some of the autogenerated README content and make sure our manual sections are using the right syntax. Once we merge and regenerate, 0.26.0 will be published.
=> chore: Update README and cut 0.26.0 for publishing

CHANGELOG.md, _test_unstructured_client/integration/test_decorators.py, gen.yaml, src/unstructured_client/_hooks/custom/split_pdf_hook.py
Fixes #191. Due to a limitation in our templated codebase, we need our split page logic to return a request that's just going to give a 200 response. Then, we jump back into the AfterSuccessHook and await all of the pdf splits. Hopefully we can clean this up soon to avoid having an extra call at all, but for now let's make sure the GET /general/docs is done on the correct base url.
=> fix: Use configured server_url for split page dummy request

src/unstructured_client/_hooks/custom/split_pdf_hook.py
Increased the default timeout for partition calls to 60 minutes.
=> increase client timeout to 60 minutes

gen.yaml
Adds `aiofiles` deps to `gen.yaml` file so they are not overwritten by the Generate workflow.
=> fix: added missing dependencies to gen.yaml file

.gitignore, _test_unstructured_client/integration/test_decorators.py, _test_unstructured_client/unit/test_split_pdf_hook.py, _test_unstructured_client/unit_utils.py, src/unstructured_client/_hooks/custom/form_utils.py, src/unstructured_client/_hooks/custom/split_pdf_hook.py
Closes #213 and makes small improvements.
=> fix: DATA_DIR_KEY

_test_unstructured_client/integration/test_integration.py
Update `test_integration` as we deprecated the freemium.
=> test: move from freemium to platform api

_test_contract/platform_api/test_jobs.py
We have a JobStatus schema as of https://github.com/Unstructured-IO/unstructured-python-client/pull/242
We need to change the mocked "active" to one of the valid job statuses.
=> fix: Fix job status in contract tests

overlay_client.yaml
This is to hold us over until these are updated on the backend. Add overlay config to remove existing schemas and recreate with a new name. This is a really ugly bandaid, we don't want to store actual schemas in this file for any longer than we have to.
Some tests are broken because we merged the schemas that we don't want, this should fix that on the next generate job.
Changes:
Onedrive -> OneDrive
Kafka-cloud -> KafkaCloud
gcs -> GCS
Google_drive -> GoogleDrive
=> chore: Clean up some connector schemas in the overlay file

.github/workflows/ci.yaml, Makefile, poetry.lock, pyproject.toml
fix issues on main CI:
* test_contract (3.9) stuck 6hrs... should really be just 30s
* test_integration (3.9) failling but not on other version
hopefully can speed up CI a bit with `pytest -n auto` (Automatically run your tests in parallel across all available CPU cores) -> ubuntu-latest has 2 core CPU so should be able to speed up in half?
note:
* maybe could be faster if we switch to our own github runner? (if it has more core)
=> feat: fix CI failing issues

_test_unstructured_client/unit/test_custom_hooks.py
that `any` line was never executed before since the error is throw after `session.general.partition`
=> fix: correct test there is no free-api log

_test_unstructured_client/unit/test_encryption.py, gen.yaml, src/unstructured_client/users.py
Add a `users.encrypt_secret` that conforms to Unstructured's secret formats. This will allow users to encrypt credentials locally before using them in connector config.
=> feat: add a encrypt_secret helper function
